syntax = "proto3";

package uni_track_source_tfms_plot_schema.proto;

import "uni_track_plot_schema/proto/plot.proto";
import "uni_track_source_tfms_plot_schema/proto/common.proto";


// Some less obvious descriptions taken out of the schema

message TFMSOceanicReportPlot {
    uni_track_plot_schema.proto.plot.Common common = 1;
    uni_track_source_tfms_plot_schema.proto.FLTDMessageAttributes fltd_message_attributes = 2;
    uni_track_source_tfms_plot_schema.proto.QualifiedAircraftID qualified_aircraft_id = 3;

    // reported position data is fully contained inside common. There's no
    // not-common information in tfms oceanic report
    // however, we need to have a field for partitioning in BQ in top level
    // message, since nested fields cannot be used for partitioning
    int64 position_timestamp = 4;
}
